//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertData", ReplyAction="*")]
        WebApplication1.ServiceReference1.InsertDataResponse InsertData(WebApplication1.ServiceReference1.InsertDataRequest request);
        
        // CODEGEN: Generating message contract since element name StudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Students", ReplyAction="*")]
        WebApplication1.ServiceReference1.StudentsResponse Students(WebApplication1.ServiceReference1.StudentsRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRecord", ReplyAction="*")]
        WebApplication1.ServiceReference1.DeleteRecordResponse DeleteRecord(WebApplication1.ServiceReference1.DeleteRecordRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchRecord", ReplyAction="*")]
        WebApplication1.ServiceReference1.SearchRecordResponse SearchRecord(WebApplication1.ServiceReference1.SearchRecordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertData", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.InsertDataRequestBody Body;
        
        public InsertDataRequest() {
        }
        
        public InsertDataRequest(WebApplication1.ServiceReference1.InsertDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string City;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Subject;
        
        public InsertDataRequestBody() {
        }
        
        public InsertDataRequestBody(string Name, int Age, string Email, string Gender, string City, string Subject) {
            this.Name = Name;
            this.Age = Age;
            this.Email = Email;
            this.Gender = Gender;
            this.City = City;
            this.Subject = Subject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.InsertDataResponseBody Body;
        
        public InsertDataResponse() {
        }
        
        public InsertDataResponse(WebApplication1.ServiceReference1.InsertDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertDataResult;
        
        public InsertDataResponseBody() {
        }
        
        public InsertDataResponseBody(int InsertDataResult) {
            this.InsertDataResult = InsertDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Students", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.StudentsRequestBody Body;
        
        public StudentsRequest() {
        }
        
        public StudentsRequest(WebApplication1.ServiceReference1.StudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StudentsRequestBody {
        
        public StudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.StudentsResponseBody Body;
        
        public StudentsResponse() {
        }
        
        public StudentsResponse(WebApplication1.ServiceReference1.StudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.ServiceReference1.Student[] StudentsResult;
        
        public StudentsResponseBody() {
        }
        
        public StudentsResponseBody(WebApplication1.ServiceReference1.Student[] StudentsResult) {
            this.StudentsResult = StudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRecord", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.DeleteRecordRequestBody Body;
        
        public DeleteRecordRequest() {
        }
        
        public DeleteRecordRequest(WebApplication1.ServiceReference1.DeleteRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        public DeleteRecordRequestBody() {
        }
        
        public DeleteRecordRequestBody(string Email) {
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.DeleteRecordResponseBody Body;
        
        public DeleteRecordResponse() {
        }
        
        public DeleteRecordResponse(WebApplication1.ServiceReference1.DeleteRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteRecordResult;
        
        public DeleteRecordResponseBody() {
        }
        
        public DeleteRecordResponseBody(int DeleteRecordResult) {
            this.DeleteRecordResult = DeleteRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchRecord", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.SearchRecordRequestBody Body;
        
        public SearchRecordRequest() {
        }
        
        public SearchRecordRequest(WebApplication1.ServiceReference1.SearchRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        public SearchRecordRequestBody() {
        }
        
        public SearchRecordRequestBody(string Email) {
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.SearchRecordResponseBody Body;
        
        public SearchRecordResponse() {
        }
        
        public SearchRecordResponse(WebApplication1.ServiceReference1.SearchRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.ServiceReference1.Student[] SearchRecordResult;
        
        public SearchRecordResponseBody() {
        }
        
        public SearchRecordResponseBody(WebApplication1.ServiceReference1.Student[] SearchRecordResult) {
            this.SearchRecordResult = SearchRecordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.WebService1Soap>, WebApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.InsertDataResponse WebApplication1.ServiceReference1.WebService1Soap.InsertData(WebApplication1.ServiceReference1.InsertDataRequest request) {
            return base.Channel.InsertData(request);
        }
        
        public int InsertData(string Name, int Age, string Email, string Gender, string City, string Subject) {
            WebApplication1.ServiceReference1.InsertDataRequest inValue = new WebApplication1.ServiceReference1.InsertDataRequest();
            inValue.Body = new WebApplication1.ServiceReference1.InsertDataRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Age = Age;
            inValue.Body.Email = Email;
            inValue.Body.Gender = Gender;
            inValue.Body.City = City;
            inValue.Body.Subject = Subject;
            WebApplication1.ServiceReference1.InsertDataResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).InsertData(inValue);
            return retVal.Body.InsertDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.StudentsResponse WebApplication1.ServiceReference1.WebService1Soap.Students(WebApplication1.ServiceReference1.StudentsRequest request) {
            return base.Channel.Students(request);
        }
        
        public WebApplication1.ServiceReference1.Student[] Students() {
            WebApplication1.ServiceReference1.StudentsRequest inValue = new WebApplication1.ServiceReference1.StudentsRequest();
            inValue.Body = new WebApplication1.ServiceReference1.StudentsRequestBody();
            WebApplication1.ServiceReference1.StudentsResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).Students(inValue);
            return retVal.Body.StudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.DeleteRecordResponse WebApplication1.ServiceReference1.WebService1Soap.DeleteRecord(WebApplication1.ServiceReference1.DeleteRecordRequest request) {
            return base.Channel.DeleteRecord(request);
        }
        
        public int DeleteRecord(string Email) {
            WebApplication1.ServiceReference1.DeleteRecordRequest inValue = new WebApplication1.ServiceReference1.DeleteRecordRequest();
            inValue.Body = new WebApplication1.ServiceReference1.DeleteRecordRequestBody();
            inValue.Body.Email = Email;
            WebApplication1.ServiceReference1.DeleteRecordResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).DeleteRecord(inValue);
            return retVal.Body.DeleteRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.SearchRecordResponse WebApplication1.ServiceReference1.WebService1Soap.SearchRecord(WebApplication1.ServiceReference1.SearchRecordRequest request) {
            return base.Channel.SearchRecord(request);
        }
        
        public WebApplication1.ServiceReference1.Student[] SearchRecord(string Email) {
            WebApplication1.ServiceReference1.SearchRecordRequest inValue = new WebApplication1.ServiceReference1.SearchRecordRequest();
            inValue.Body = new WebApplication1.ServiceReference1.SearchRecordRequestBody();
            inValue.Body.Email = Email;
            WebApplication1.ServiceReference1.SearchRecordResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).SearchRecord(inValue);
            return retVal.Body.SearchRecordResult;
        }
    }
}
